### ISSUE TITLE
"vanillacloud.net" gives 'IP not found" error

### ISSUE THREAD

**Issue by OldGrama** [OldGrama/VanillaHub#4]
**Describe the bug**
web browser does not redirect when no subdomain is provided for the vanillacloud.net website

**To Reproduce**
1. Go to web browser
2. in address bar, type "vanillacloud.net"
3. no IP found for vanillacloud.net

**Expected behavior**
redirect to the correct subdomain for the website (such as store.vanillacloud.net)

**Screenshots**
https://i.imgur.com/BCHPX2P.png

**Minecraft Version (as well as any clients or mods you use such as badlion or fabric loader)**
n/a

**Additional context**
this does not happen on the vanillapod.net website

**Comment by EmeryxWildfire** [comment]
Should be fixed, just waiting for the change to propagate .

**Comment by OldGrama** [comment]
Thank you! will mark as solved when I am able to connect using vanillacloud.net

**Comment by OldGrama** [comment]
still unable to connect, how long does propagation usually take?

**Comment by OldGrama** [comment]
Unable to confirm if changes did not have an effect, or if they have not been propagated.

**Comment by jnx-02** [comment]
Typing "vanillacloud.net" will work now and it will redirect to "store.vanillacloud.net"

Resolved
